### ISSUE TITLE
Many methods don't pass credentials which causes auth errors

### ISSUE THREAD

**Issue by vkras** [milvus-io/milvus-sdk-csharp#17]
DescribeIndex, FlushAsync etc fail with auth errors.
Pull request is created:

https://github.com/milvus-io/milvus-sdk-csharp/pull/16

**Comment by vkras** [comment]
@weianweigan Could you rebuild the package with the latest fixes? We are trying to use it for our project.

**Comment by weianweigan** [comment]
> @weianweigan Could you rebuild the package with the latest fixes? We are trying to use it for our project.

OK I will publish nuget package.
