### ISSUE TITLE
about Nuget package

### ISSUE THREAD

**Issue by weianweigan** [milvus-io/milvus-sdk-csharp#2]
@yhmo 
I found that a action failed because of a missing field.
In c# project,we use [nuget](https://www.nuget.org/) as default package manager. There is a github workflow named [NugetPublish](https://github.com/milvus-io/milvus-sdk-csharp/blob/main/.github/workflows/NugetPublish.yml).I use it to push package.
There is a secret field used in [NugetPublish.yml](https://github.com/milvus-io/milvus-sdk-csharp/blob/main/.github/workflows/NugetPublish.yml),but i cannot find it in this repos's settings area.
How could i set this field just like this or you can  help me to set it?
![image](https://user-images.githubusercontent.com/25452811/183249950-61e8d9f1-9d63-46e6-9605-0e32cf51f0d9.png)

**Comment by yhmo** [comment]
Yes, I can help to set it. You can send email to tell me how to do it.

**Comment by yhmo** [comment]
@weianweigan 
The secret key has been added.
