### ISSUE TITLE
Milvus vs Pinecone

### ISSUE THREAD

**Issue by securigy** [milvus-io/milvus-sdk-csharp#24]
Pardon for asking... beginners questions - but I am coming from implementing Pinecone in my application and would like to implement Milvus as well, as an option for the user to choose the vector DB that can be run locally... However, I stumble on some immediate questions:

1. Is the Collection here equivalent to Index on Pinecone? (the Collection in Pinecone is used for snapshots of vectors in the Index). Ans what is Index in Milvus? Where do I find basic definition of the terminology being used?
2. If I intend to run Milvus locally, is my endpoint: "https://localhost:19530" ?
3. I installed WSL2 and Ubuntu, I also install NuGet package in my project in VS2022, however, can you please clarify to connection/link between this and the DB itself - how do I make it run or make sure it is running? I cannot find anything in the documentation pertaining to C# SDK - I know that my WSL2 is running because I see it on the screen...

**Comment by weianweigan** [comment]
No@securigy Welcome！
> Is the Collection here equivalent to Index on Pinecone? (the Collection in Pinecone is used for snapshots of vectors in the Index). Ans what is Index in Milvus? Where do I find basic definition of the terminology being used?

Maybe not! In milvus you need create a collection which first. Then you can create an _[index](https://milvus.io/docs/index.md)_ for search. You can visit [milvus doc site](https://milvus.io/docs) for more information.

> If I intend to run Milvus locally, is my endpoint: "https://localhost:19530" ?

Yes the default endpoint is https://localhost:19530. It is a grpc url. You can use it communicate with milvus. You can open [this url ](https://milvus.io/docs/manage_connection.md)for more.

> I installed WSL2 and Ubuntu, I also install NuGet package in my project in VS2022, however, can you please clarify to connection/link between this and the DB itself - how do I make it run or make sure it is running? I cannot find anything in the documentation pertaining to C# SDK - I know that my WSL2 is running because I see it on the screen...

You can use health method to check milvus server state.

**Comment by securigy** [comment]
What I meant by the last question is simply how do I make Milvus server run?

**Comment by weianweigan** [comment]
> What I meant by the last question is simply how do I make Milvus server run? 

@securigy you can use docker compose to run milvus. 
```
sudo docker-compose up -d
```
Check this [url](https://milvus.io/docs/install_standalone-docker.md). If you have some trouble. You can choose [zilliz cloud](https://zilliz.com/cloud) as a begin.

**Comment by weianweigan** [comment]
[Milvus lite](https://github.com/milvus-io/milvus-lite) is also a choose for locally run milvus.

**Comment by securigy** [comment]
OK, thank you, I will check it out. I was looking for something I can run locally. I already run Pinecone API to their service but now need something local for privacy. I will try the links you posted. Thanks again.

**Comment by securigy** [comment]
So I followed the instructions:

and you can see that after I installed WSL2, I successfully downloaded docker-compose.yml - all this within WSL2 command window. It is not clear where did it fo, since further instructions trials are failing:

`**Installing, this may take a few minutes...
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: securigy
New password:
Retype new password:
passwd: password updated successfully
Installation successful!
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.15.90.1-microsoft-standard-WSL2 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage


This message is shown once a day. To disable it please create the
/home/securigy/.hushlogin file.
securigy@AsusROG:~$ wget https://github.com/milvus-io/milvus/releases/download/v2.2.11/milvus-standalone-docker-compose.yml -O docker-compose.yml
--2023-07-02 19:41:25--  https://github.com/milvus-io/milvus/releases/download/v2.2.11/milvus-standalone-docker-compose.yml
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: 
.............................ype=application%2Foctet-stream [following]
--2023-07-02 19:41:25--  
.......................cation%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1357 (1.3K) [application/octet-stream]
Saving to: ‘docker-compose.yml’

docker-compose.yml            100%[=================================================>]   1.33K  --.-KB/s    in 0s

2023-07-02 19:41:26 (161 MB/s) - ‘docker-compose.yml’ saved [1357/1357]**
`

Any advise?

**Comment by weianweigan** [comment]
@securigy it seems that you downloaded yml file. You can run docker-compose up command in the directory that the yml file exists. Make sure docker and docker-compose installed in your wsl.

**Comment by securigy** [comment]
As I mentioned before, I started from this:
[https://github.com/milvus-io/milvus-sdk-csharp/blob/main/docs/readme.md](url)

Then proceeded to this:
[https://github.com/milvus-io/milvus](url)

Then according to the following I downloaded and installed WLS2 on my Win11 
[https://milvus.io/docs/prerequisite-docker.md](url)
I also installed the latest Ubuntu 22.x.x on WLS2.

Then I installed Docker Compose Desktop on WSL2:
![image](https://github.com/milvus-io/milvus-sdk-csharp/assets/22898824/e09f1fa6-dd80-41b6-82c2-5612b31166f3)

and now after I continued the instructions, I downloaded this yml file, assuming it got downloaded to the current directory, and indeed it is there... but when I execute
`sudo docker-compose up -d`

I get:
`sudo: docker-compose: command not found`

I don't understand why. What instructions or steps did I miss?
The command Linux window indicates that WLS2 with Ubuntu in it is running and Docker Desktop window is on... what is missing and how?

**Comment by weianweigan** [comment]
@securigy Docker-compose is a python package. You need to install it. 
Try this [doc](https://do.docker.com/compose/install/linux/#install-using-the-repository).
Or [this](https://docs.docker.com/compose/install/standalone/).

After docker-compose installed, you can try docker-compose up again.
