### ISSUE TITLE
Milvus 2.3

### ISSUE THREAD

**Issue by lofcz** [milvus-io/milvus-sdk-csharp#31]
Milvus 2.3 was released recently, we would like to upgrade our version due to the GPU support.
There are some breaking changes, so the C# SDK must also be updated. Is the support for the new version currently in the works? It would help us immensely to know whether we can expect the SDK to be updated in a week, a month, or later.

**Comment by weianweigan** [comment]
Thanks for your attention.We have just completed the update for v2.2. I have reviewed the updates for v2.3, but I haven't started the update process yet. It may take two to three weeks, and I'm not entirely sure at the moment.

**Comment by lofcz** [comment]
First batch of work done in #42 by @roji

**Comment by roji** [comment]
@weianweigan I created issues for the various 2.3.0 work and placed them in a new [milestone](https://github.com/milvus-io/milvus-sdk-csharp/milestone/2) - please take a look (don't hesitate to open additional issues if I missed anything).

I think we can close this issue now, as the milestone tracks work needed 2.3.0.

**Comment by weianweigan** [comment]
@roji I have reviewed the issues you created for version 2.3.0 and the new milestone. Thank you for organizing them. 

I agree that we can close the current issue now, as the new milestone is tracking the work needed for version 2.3.0.
