### ISSUE TITLE
collection not loaded: unrecoverable error: fail to search on all shard leaders

### ISSUE THREAD

**Issue by othmanjad** [milvus-io/milvus-sdk-csharp#33]
i have a eroor when i use the same example in the document(book example )
Milvus.Client.MilvusException
  HResult=0x80131500
  Message=ErrorCode: UnexpectedError Reason: attempt #0: fail to get shard leaders from QueryCoord: collection=443943362921669896: collection not loaded: unrecoverable error: fail to search on all shard leaders
  Source=Milvus.Client
  StackTrace:
   at Milvus.Client.MilvusClient.<InvokeAsync>d__34`2.MoveNext()
   at Milvus.Client.MilvusCollection.<SearchAsync>d__18`1.MoveNext()
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__Search|2>d.MoveNext() in D:\Users\User\Source\Repos\Ais\Ais\Program.cs:line 96
   at Program.<<Main>$>d__0.MoveNext() in D:\Users\User\Source\Repos\Ais\Ais\Program.cs:line 32

**Comment by weianweigan** [comment]
It seems that collection has not loaded. Have you call loadcollection method before search?

```c#
await milvusClient.LoadCollectionAsync(collectionName);
```

**Comment by othmanjad** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'MilvusClient' does not contain a definition for 'LoadCollectionAsync' and no accessible extension method

**Comment by othmanjad** [comment]
> 'collection not loaded: unrecoverable error: fail to search on all shard leaders'
> 
> It seems that collection has not loaded. Have you call loadcollection method before search?
> 
> ```cs
> await milvusClient.LoadCollectionAsync(collectionName);
> ```

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'MilvusClient' does not contain a definition for 'LoadCollectionAsync' and no accessible extension method

**Comment by weianweigan** [comment]
The api changed, try this new usage.

```
MilvusCollection collection = milvusClient.GetCollection(collectionName);

collection.LoadCollectionAsync();

```
