### ISSUE TITLE
你好我想咨询一下，一般怎么提取图片向量然后插入，可以给个Demo吗 | Hello, I want to consult, generally how to extract the picture vector and then insert, can give a Demo

### ISSUE THREAD

**Issue by NingLiu1998** [milvus-io/milvus-sdk-csharp#46]
这是我之前获取图片向量的方式 | This is how I got the image vector before
![image](https://github.com/milvus-io/milvus-sdk-csharp/assets/109678937/43843348-c324-4214-ad6c-13067224f365)

我该怎么结合 [milvus-sdk-csharp](https://github.com/milvus-io/milvus-sdk-csharp) 来使用，有demo吗

How should I combine [milvus - SDK - csharp] (https://github.com/milvus-io/milvus-sdk-csharp) to use, have a demo

**Comment by weianweigan** [comment]
看一下[milvus bootcamp](https://github.com/towhee-io/examples/blob/main/image/reverse_image_search/1_build_image_search_engine.ipynb) ？

**Comment by NingLiu1998** [comment]
> 看一下[milvus bootcamp](https://github.com/towhee-io/examples/blob/main/image/reverse_image_search/1_build_image_search_engine.ipynb) ？

他这个我试过，用py调模型提取图片特征向量，但是同样的操作在.Net上我没有头绪怎么弄
