### ISSUE TITLE
文档示例代码有错误

### ISSUE THREAD

**Issue by NingLiu1998** [milvus-io/milvus-sdk-csharp#47]
# Look Image

![image](https://github.com/milvus-io/milvus-sdk-csharp/assets/109678937/5d25ebfa-bbbe-4518-a162-1eda152d03f9)

# Same as the document

![image](https://github.com/milvus-io/milvus-sdk-csharp/assets/109678937/d7059920-160b-4593-ad5b-32310f61d21e)

Package version ： 2.2.2-preview.6

![image](https://github.com/milvus-io/milvus-sdk-csharp/assets/109678937/1a2e17a7-0f61-4d07-a9de-7388833e0e00)

**Comment by weianweigan** [comment]
感谢反馈，应该是：
```c#
collection.LoadCollectionAsync(collectionName);
```
