### ISSUE TITLE
sdk 2.0.1 insert exception： num_rows(0) should be greater than 0

### ISSUE THREAD

**Issue by 591094733** [milvus-io/milvus-sdk-csharp#48]
num_rows(0) should be greater than 0

**Comment by weianweigan** [comment]
SDK v2.0.1? Is this version right? Cloud you provide more information about this?

**Comment by 591094733** [comment]
Hi, 

Thank you for your reply!

![image](https://github.com/milvus-io/milvus-sdk-csharp/assets/7984311/4d378fa3-ca4b-43cf-95a7-7f44aefbd664)

Visual Studio 2022 Nuget package version.

I can't see the latest version, it could also be an environmental issue for me.

**Comment by weianweigan** [comment]
@591094733 It is not right package. You need use [this](https://www.nuget.org/packages/Milvus.Client/). Maybe you have not check pre-release in visual studio nuget package manager so it did not appeared.

**Comment by 591094733** [comment]
Thank you for your patient answer,

I have also discovered and solved it. Is there any example of a search/query about “MilvusDataType.FloatVector” field?

**Comment by weianweigan** [comment]
> Thank you for your patient answer,
> 
> I have also discovered and solved it. Is there any example of a search/query about “MilvusDataType.FloatVector” field?

There are some [notebooks](https://github.com/milvus-io/milvus-sdk-csharp/tree/main/docs/notebooks) you can try to run. And [milvus docs](https://milvus.io/docs/v2.2.x/search.md) may be helpful.
