### ISSUE TITLE
Run integration testing again Milvus 2.2 to verify SDK backwards compat

### ISSUE THREAD

**Issue by roji** [milvus-io/milvus-sdk-csharp#51]

**Comment by weianweigan** [comment]
@roji  Should we also consider testing milvus on [Zilliz Cloud](https://cloud.zilliz.com/)? It based on Milvus but seems to have some differences.  It might be more convenient for beginners to use Zilliz Cloud.

**Comment by roji** [comment]
We definitely can - do you know if SDKs for other languages do this in the CI pipeline? In any case, I suggest opening a separate issue to track and discuss that.

**Comment by roji** [comment]
I looked into this, and unfortunately setting up Milvus 2.2 is quite different from 2.3 and more complex, requiring docker-compose (not just a single docker container). I propose to let this go for now; in any case, people still stuck on 2.2 can always use the 2.2 SDK if they need to.
