### ISSUE TITLE
Add Cosine metrics support

### ISSUE THREAD

**Issue by roji** [milvus-io/milvus-sdk-csharp#53]
Milvus 2.3.0 introduced support for Cosine metrics. From the [release notes](https://github.com/milvus-io/milvus/releases/tag/v2.3.0):

> The Cosine Metrics is widely regarded as the standard method for measuring the distance between vectors, particularly in Large Language Models (LLMs). With the release of Milvus 2.3.0, cosine metrics are now natively supported. As a result, users no longer need to quantize vectors for IP (Inner Product) metrics.

**Comment by MarioMartinPlaza** [comment]
Thanks for add The Cosine Metrics!
