### ISSUE TITLE
String type in Field.Create return compile error string cannot be nullable

### ISSUE THREAD

**Issue by sandraplato1234** [milvus-io/milvus-sdk-csharp#6]
Hi,
I got a compiler error when trying to create a string field
Field.Create("test","firsttest")
return TDATA canot be nullable
Thanks in advance

**Comment by awharrison-28** [comment]
+1 it seems like this restriction can and should be lifted since the field type can be created as string when defining the collection schema at collection creation.

**Comment by tawalke** [comment]
@luisquintanilla This was also what we were looking at with SDK possibilities. Based upon last response here let's discuss what we should or shouldn't do on next week.

**Comment by LadyNaggaga** [comment]
I work on ASP.NET and C# would like to discuss this further. Is there a slack channel our team can join so, we can have discussion

**Comment by tawalke** [comment]
> > @luisquintanilla @LadyNaggaga This is also something that what we were looking/discussed at with SDK possibilities. Based upon last response here let's discuss what we should or shouldn't do on next week.
> 
> I work on ASP.NET and C# would like to discuss this further. Is there a slack channel our team can join so, we can have discussion

@LadyNaggaga I created a channel already for us  in Milvus for follow-up & invited you to the follow-up with Luis

**Comment by minhhieugma** [comment]
can someone give me the slack link? the link from the main project is broken. I want to contribute to this .net sdk

**Comment by minhhieugma** [comment]
I make a PR to fix this issue here https://github.com/milvus-io/milvus-sdk-csharp/pull/9

**Comment by tawalke** [comment]
> can someone give me the slack link? the link from the main project is broken. I want to contribute to this .net sdk

I believe Slack channel info is provided here: https://milvus.io/community
