### ISSUE TITLE
Support array fields

### ISSUE THREAD

**Issue by BlackGad** [milvus-io/milvus-sdk-csharp#77]
Current client API does not allow you to specify field schema for `Array` types.

I propose extending the C# API to include support for defining array field schemas, which would allow developers to specify the type of elements in the array along with constraints such as `capacity` and `maxLength`. Below are proposed methods to add to the API for defining array fields with both varchar and scalar types:

```
FieldSchema.CreateVarcharArray("field_id", capacity: 200, maxLength: 255, description: "Array of varchars"),
FieldSchema.CreateArray<float>("field_id", capacity: 200, description: "Array of scalar types")
```

**Comment by roji** [comment]
Thanks. Yeah, the SDK was originally developed against 2.2, and arrays were only introduced against 2.3 - we missed this. We'll take a look at implementing it.

**Comment by BlackGad** [comment]
As well as iterators. Crucial thing for our needs.

**Comment by BlackGad** [comment]
PR with an implementation https://github.com/milvus-io/milvus-sdk-csharp/pull/81
