### ISSUE TITLE
Grpc.Core throws HttpRequestException(Requesting HTTP version 2.0)

### ISSUE THREAD

**Issue by MayDay-wpf** [milvus-io/milvus-sdk-csharp#86]
I deployed Milvus on a remote server and called API using SDK【Grpc.Core.RpcException:“Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.")”】

**Comment by weianweigan** [comment]
@MayDay-wpf  Are you using .net frameworks ?

**Comment by MayDay-wpf** [comment]
> @MayDay-wpf 您使用 .net 框架吗？
> 
> > [.NET 支持的平台上的 gRPC](https://learn.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-8.0)

No, my client is using this. The net6, the CentOS7 used by the server, is deployed with the docker

**Comment by weianweigan** [comment]
@MayDay-wpf  If your project based on .NET 6 is throwing an exception, could you provide more details on how to reproduce the issue?

**Comment by MayDay-wpf** [comment]
> @MayDay-wpf If your project based on .NET 6 is throwing an exception, could you provide more details on how to reproduce the issue?

Using a console application as an example, I encountered this exception when checking the health status of Milvus locally. I am not sure if it's an issue with my server configuration. However, it's strange that I can access the Milvus on my server normally using RESTful API. Could it be because my server does not support HTTP/2?

**Comment by weianweigan** [comment]
> > @MayDay-wpf If your project based on .NET 6 is throwing an exception, could you provide more details on how to reproduce the issue?
> 
> Using a console application as an example, I encountered this exception when checking the health status of Milvus locally. I am not sure if it's an issue with my server configuration. However, it's strange that I can access the Milvus on my server normally using RESTful API. Could it be because my server does not support HTTP/2?

@MayDay-wpf  It seems that client doesn't support http2. Considering that you are using .net6 which supports http2 in your console app, so it's weird.

**Comment by weianweigan** [comment]
Caused by network enviroment.
